# Generated by Django 4.1 on 2023-08-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("section", models.IntegerField()),
                ("password", models.CharField(max_length=100)),
                ("confirm_password", models.CharField(max_length=100)),
            ],
            options={"db_table": "User_details",},
        ),
        migrations.CreateModel(
            name="User_medical_profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=20)),
                ("dob", models.DateField(max_length=8)),
                ("contact", models.IntegerField()),
                ("email", models.EmailField(max_length=100)),
                ("street", models.TextField()),
                ("weight", models.IntegerField()),
                ("height", models.IntegerField()),
                ("allergies", models.TextField()),
                ("medicalConditions", models.TextField()),
                ("medications", models.TextField()),
                ("surgeries", models.TextField()),
                ("familyHistory", models.TextField()),
                ("checkup", models.DateField()),
                ("emergencyContactName", models.TextField()),
                ("emergencyRelationship", models.TextField()),
                ("emergencyContactNumber", models.IntegerField()),
                ("consentCheckbox", models.CharField(max_length=100)),
            ],
            options={"db_table": "User",},
        ),
    ]
