# Generated by Django 4.1 on 2023-08-08 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Behealthy", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user_medical_profile", table="User_medical_profile",
        ),
    ]
