# Generated by Django 4.1 on 2023-08-09 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Behealthy", "0006_alter_user_medical_profile_emergencycontactnumber"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_medical_profile", name="consentCheckbox",
        ),
    ]
