# Generated by Django 4.1 on 2023-08-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Behealthy", "0007_remove_user_medical_profile_consentcheckbox"),
    ]

    operations = [
        migrations.CreateModel(
            name="Login_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=100)),
                ("confirm_password", models.CharField(max_length=100)),
            ],
            options={"db_table": "Login_details",},
        ),
    ]
